general.import = [
    "~/.config/alacritty/themes/catppuccin-latte.toml"
]

[window]
startup_mode = "Maximized"

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
bold = { family = "CommitMono Nerd Font", style = "Bold" }
italic = { family = "CommitMono Nerd Font", style = "Italic" }
bold_italic = { family = "CommitMono Nerd Font", style = "BoldItalic" }

[keyboard]
bindings = [
# Disable New Tab (MacOS thing)
{ key = 'T', mods = "Command", action = 'None'},
{ key = 'Enter', mods = "Alt", action = 'None'},
{ key = 'Left', mods = "Alt", chars = "\u001BB"},
{ key = 'Right', mods = "Alt", chars = "\u001BF"},
]

