[window]
startup_mode = "Maximized"

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
bold = { family = "CommitMono Nerd Font", style = "Bold" }
italic = { family = "CommitMono Nerd Font", style = "Italic" }
bold_italic = { family = "CommitMono Nerd Font", style = "BoldItalic" }

[keyboard]
# Disable New Tab (MacOS thing)
bindings = [
{ key = 'T', mods = "Command", action = 'None'},
]
