require("lennart.plugins_setup")

require("lennart.core.options")
require("lennart.core.keymaps")
require("lennart.core.colorscheme")
require("lennart.core.cmd")

require("lennart.plugins.lsp-zero")
require("lennart.plugins.undotree")
require("lennart.plugins.harpoon")
require("lennart.plugins.telescope")
require("lennart.plugins.treesitter")
require("lennart.plugins.fugitive")
require("lennart.plugins.comment")
require("lennart.plugins.gitsigns")
require("lennart.plugins.nvim_tree")
require("lennart.plugins.lualine")
require("lennart.plugins.nvim-toggler")
require("lennart.plugins.dressing")
require("lennart.plugins.autopairs")
require("lennart.plugins.nvim-scroll")

