# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$git_branch$git_status $git_state
$directory$character
'''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = '\[ [$branch(:$remote_branch)]($style)[:](bold blue)'

[git_status]
up_to_date = '[✓](bold green)'
style = 'bold blue'
format = '$all_status[:]($style)$ahead_behind \]'
untracked = '[u](red)'
modified = '[m](yellow)'
staged = '[s](green)'
stashed = ''

[git_state]
format = '\[[$state( $progress_current/$progress_total)]($style)\] '
