alias vs="code ."
alias nw="~/bin/tmux_newwindow"
alias ts="~/bin/tmux_sessionizer"
alias dkcons="~/bin/docker_current_containers"
alias dkbash="~/bin/docker_run_bash_on_container"
alias dkid="~/bin/docker_container_id"
alias gre="~/bin/git_rebase"
alias gsm="git switch master"
alias vim="nvim"
alias pysrc="~/bin/python_source"
alias cht="~/bin/cht.sh"
# Commands to quickly navigate between projects
alias snap="~/bin/projects/snap"
alias symserv="ts services"
alias symapp="ts symapps"
alias dot="ts dotf"
alias hero="ts hero"
