# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-a = 'workspace A' # Alacritty
alt-p = 'workspace P' # Personal Chrome
alt-w = 'workspace W' # Work Chrome
alt-s = 'workspace S' # Slack: Main
alt-h = 'workspace H' # Slack: Huddle
alt-l = 'workspace L' # linear
alt-m = 'workspace M' # Media
alt-t = 'workspace T' # Testin Chrome
alt-z = 'workspace Z' # Zoom
alt-c = 'workspace C' # SMS / iMessage
alt-o = 'workspace O' # Obsidian
alt-d = 'workspace D' # Docker Desktop
alt-v = 'workspace V' # VS


cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

cmd-shift-a = 'move-node-to-workspace A' # Alacritty
cmd-shift-p = 'move-node-to-workspace P' # Personal Chrome
cmd-shift-w = 'move-node-to-workspace W' # Work Chrome
cmd-shift-s = 'move-node-to-workspace S' # Slack: Main
cmd-shift-h = 'move-node-to-workspace H' # Slack: Huddle
cmd-shift-l = 'move-node-to-workspace L' # linear
cmd-shift-m = 'move-node-to-workspace M' # Media
cmd-shift-z = 'move-node-to-workspace Z' # Zoom
cmd-shift-c = 'move-node-to-workspace C' # SMS / iMessage
cmd-shift-o = 'move-node-to-workspace O' # Obsidian
cmd-shift-d = 'move-node-to-workspace D' # Docker Desktop
cmd-shift-v = 'move-node-to-workspace V' # VS

alt-shift-c = 'reload-config'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = ['move-node-to-workspace A']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'personal'
run = [ 'move-node-to-workspace P']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'myeducator'
run = [ 'move-node-to-workspace W']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'media'
run = [ 'move-node-to-workspace M']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'testing'
run = [ 'move-node-to-workspace T']

[[on-window-detected]]
if.app-id = 'com.linear'
run = [ 'move-node-to-workspace L']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
if.window-title-regex-substring = '[Main]'
run = [ 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
if.window-title-regex-substring = 'Huddle'
run = [ 'move-node-to-workspace H']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = [ 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = [ 'move-node-to-workspace C' ]

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = [ 'move-node-to-workspace O' ]

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = [ 'move-node-to-workspace D' ]

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = [ 'move-node-to-workspace V' ]

[[on-window-detected]]
if.app-id = 'com.apple.DigitalColorMeter'
run = [ 'layout floating' ]


